version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: com.amazonaws:aws-java-sdk-core
        update-types: [ version-update:semver-patch ]
      - dependency-name: com.amazonaws:aws-java-sdk-s3
        update-types: [ version-update:semver-patch ]
